---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: package
    run_list:
      - recipe[taskwarrior::default]
    attributes:
  - name: source
    run_list:
      - recipe[apt::default]
      - recipe[git::default]
      - recipe[build-essential::default]
      - recipe[cmake::default]
      - recipe[taskwarrior::default]
    attributes:
      taskwarrior:
        install_method: source
