---
driver:
  name: vagrant
  driver_config:
      require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_bags_path: ./test/data_bags

platforms:
  - name: ubuntu-13.10
  - name: ubuntu-13.10-i386
  - name: debian-7.2.0
  - name: debian-7.2.0-i386

suites:
  - name: package
    run_list:
      - recipe[taskwarrior::default]
    attributes:
  - name: source
    run_list:
      - recipe[taskwarrior::default]
    attributes:
      taskwarrior:
        install_method: source
  - name: server
    run_list:
      - recipe[taskwarrior::server]
    attributes:
      taskwarrior:
        server:
          organization: Evil. Inc
