---
driver:
  name: vagrant
  driver_config:
      require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: package
    run_list:
      - recipe[taskwarrior::default]
    attributes:
  - name: source
    run_list:
      - recipe[taskwarrior::default]
    attributes:
      taskwarrior:
        install_method: source
  - name: server
    run_list:
      - recipe[taskwarrior::server]
    attributes:
